/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminActionLog { 'action' : string, 'timestamp' : string }
export interface AuditEntry {
  'changeset' : string,
  'userId' : Principal,
  'timestamp' : string,
}
export interface PhishingScanResult {
  'scanDate' : string,
  'scannedBy' : Principal,
  'trustScore' : bigint,
  'verdict' : string,
  'urlOrText' : string,
}
export interface ScanResponse { 'trustScore' : bigint, 'verdict' : string }
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'deleteScanResult' : ActorMethod<[bigint], undefined>,
  'getAdminLog' : ActorMethod<[], Array<AdminActionLog>>,
  'getAllScanResults' : ActorMethod<[], Array<PhishingScanResult>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAuditLog' : ActorMethod<[], Array<AuditEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSystemStats' : ActorMethod<
    [],
    {
      'safeCount' : bigint,
      'suspiciousCount' : bigint,
      'totalScans' : bigint,
      'phishingCount' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBanned' : ActorMethod<[Principal], boolean>,
  'readConfigValue' : ActorMethod<[string], [] | [string]>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveConfigValue' : ActorMethod<[string, string], undefined>,
  'scanUrlOrText' : ActorMethod<[string], ScanResponse>,
  'updateScanResult' : ActorMethod<[bigint, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];