/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminActionLog = IDL.Record({
  'action' : IDL.Text,
  'timestamp' : IDL.Text,
});
export const PhishingScanResult = IDL.Record({
  'scanDate' : IDL.Text,
  'scannedBy' : IDL.Principal,
  'trustScore' : IDL.Nat,
  'verdict' : IDL.Text,
  'urlOrText' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const AuditEntry = IDL.Record({
  'changeset' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Text,
});
export const ScanResponse = IDL.Record({
  'trustScore' : IDL.Nat,
  'verdict' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'deleteScanResult' : IDL.Func([IDL.Nat], [], []),
  'getAdminLog' : IDL.Func([], [IDL.Vec(AdminActionLog)], ['query']),
  'getAllScanResults' : IDL.Func([], [IDL.Vec(PhishingScanResult)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'safeCount' : IDL.Nat,
          'suspiciousCount' : IDL.Nat,
          'totalScans' : IDL.Nat,
          'phishingCount' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'readConfigValue' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConfigValue' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'scanUrlOrText' : IDL.Func([IDL.Text], [ScanResponse], []),
  'updateScanResult' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminActionLog = IDL.Record({
    'action' : IDL.Text,
    'timestamp' : IDL.Text,
  });
  const PhishingScanResult = IDL.Record({
    'scanDate' : IDL.Text,
    'scannedBy' : IDL.Principal,
    'trustScore' : IDL.Nat,
    'verdict' : IDL.Text,
    'urlOrText' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const AuditEntry = IDL.Record({
    'changeset' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Text,
  });
  const ScanResponse = IDL.Record({
    'trustScore' : IDL.Nat,
    'verdict' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'deleteScanResult' : IDL.Func([IDL.Nat], [], []),
    'getAdminLog' : IDL.Func([], [IDL.Vec(AdminActionLog)], ['query']),
    'getAllScanResults' : IDL.Func(
        [],
        [IDL.Vec(PhishingScanResult)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'safeCount' : IDL.Nat,
            'suspiciousCount' : IDL.Nat,
            'totalScans' : IDL.Nat,
            'phishingCount' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'readConfigValue' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConfigValue' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'scanUrlOrText' : IDL.Func([IDL.Text], [ScanResponse], []),
    'updateScanResult' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };